version: "2.9"

services:
  sql-server:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    networks:
      - sql-network
    ports:
      - "1401:1433"
    environment:
      SA_PASSWORD: "Arman123!"
      ACCEPT_EULA: "Y"

  migrations:
    build:
      context: .
    expose:
      - 88
    depends_on:
      sql-server:
        condition: service_started
    networks:
      - sql-network
    restart: on-failure
    environment:
      CONNECTION_STRING: "Server=mssql,1433; Database=Test;User Id=sa; Password=Arman123!;"

networks:
  sql-network:
    name: sql-network